"""DWG/DXF 비교 결과 HTML 리포트 생성기

Sprint 9 Phase 3.3: DwgReportGenerator
비교 결과를 HTML 리포트로 생성합니다.

기능:
    - HTML 리포트 생성
    - 변경점 목록 테이블
    - 통계 차트 (선택)
"""

import base64
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import numpy as np

from .dxf_comparator import DxfChange, DxfChangeType, DxfComparisonResult

logger = logging.getLogger(__name__)


class DwgReportGenerator:
    """DWG/DXF 비교 결과 HTML 리포트 생성기

    사용 예시:
        generator = DwgReportGenerator()
        generator.generate(result, diff_image, "report.html")
    """

    HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DWG/DXF 비교 리포트</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: 'Segoe UI', Tahoma, sans-serif; 
            background: #1a1a2e; 
            color: #eee; 
            padding: 20px;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ 
            color: #00d9ff; 
            margin-bottom: 20px; 
            border-bottom: 2px solid #00d9ff;
            padding-bottom: 10px;
        }}
        h2 {{ color: #a855f7; margin: 20px 0 10px; }}
        .summary {{ 
            background: #16213e; 
            padding: 20px; 
            border-radius: 10px; 
            margin-bottom: 20px;
            display: flex;
            gap: 20px;
        }}
        .stat-card {{
            background: #0f3460;
            padding: 15px 25px;
            border-radius: 8px;
            text-align: center;
            min-width: 120px;
        }}
        .stat-card .number {{
            font-size: 2em;
            font-weight: bold;
        }}
        .stat-card.added .number {{ color: #00ff00; }}
        .stat-card.deleted .number {{ color: #ff4444; }}
        .stat-card.total .number {{ color: #00d9ff; }}
        table {{ 
            width: 100%; 
            border-collapse: collapse; 
            margin: 10px 0;
        }}
        th, td {{ 
            padding: 12px; 
            text-align: left; 
            border-bottom: 1px solid #333;
        }}
        th {{ background: #0f3460; color: #00d9ff; }}
        tr:hover {{ background: #16213e; }}
        .badge {{
            padding: 3px 10px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }}
        .badge.added {{ background: #00ff00; color: #000; }}
        .badge.deleted {{ background: #ff4444; color: #fff; }}
        .badge.modified {{ background: #ffa500; color: #000; }}
        .image-container {{
            margin: 20px 0;
            text-align: center;
        }}
        .image-container img {{
            max-width: 100%;
            border-radius: 10px;
            border: 2px solid #333;
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📐 DWG/DXF 비교 리포트</h1>
        
        <div class="summary">
            <div class="stat-card total">
                <div class="number">{total_changes}</div>
                <div>총 변경점</div>
            </div>
            <div class="stat-card added">
                <div class="number">{added_count}</div>
                <div>추가</div>
            </div>
            <div class="stat-card deleted">
                <div class="number">{deleted_count}</div>
                <div>삭제</div>
            </div>
        </div>
        
        <h2>📋 파일 정보</h2>
        <table>
            <tr><td>기준 파일 (Old)</td><td>{source_a}</td></tr>
            <tr><td>대상 파일 (New)</td><td>{source_b}</td></tr>
            <tr><td>비교 일시</td><td>{timestamp}</td></tr>
        </table>
        
        {diff_image_section}
        
        <h2>📝 변경 목록</h2>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>변경 유형</th>
                    <th>엔티티 타입</th>
                    <th>레이어</th>
                    <th>위치</th>
                </tr>
            </thead>
            <tbody>
                {changes_rows}
            </tbody>
        </table>
        
        <div class="footer">
            Generated by TEKLA_MCP DWG Comparison Engine | {timestamp}
        </div>
    </div>
</body>
</html>"""

    def generate(
        self,
        result: DxfComparisonResult,
        source_a: str,
        source_b: str,
        output_path: Path,
        diff_image: Optional[np.ndarray] = None,
    ) -> Path:
        """HTML 리포트 생성

        Args:
            result: 비교 결과
            source_a: 기준 파일 경로
            source_b: 대상 파일 경로
            output_path: 출력 HTML 경로
            diff_image: 차이 이미지 (선택)

        Returns:
            생성된 HTML 파일 경로
        """
        output_path = Path(output_path)

        # 변경 목록 HTML 생성
        changes_rows = self._generate_changes_rows(result.changes)

        # 차이 이미지 섹션
        diff_image_section = ""
        if diff_image is not None:
            diff_image_section = self._generate_image_section(diff_image)

        # HTML 생성
        html = self.HTML_TEMPLATE.format(
            total_changes=result.total_changes,
            added_count=result.added_count,
            deleted_count=result.deleted_count,
            source_a=source_a,
            source_b=source_b,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            diff_image_section=diff_image_section,
            changes_rows=changes_rows,
        )

        # 파일 저장
        output_path.write_text(html, encoding="utf-8")

        logger.info(f"HTML 리포트 생성: {output_path}")
        return output_path

    def _generate_changes_rows(self, changes: List[DxfChange]) -> str:
        """변경 목록 테이블 행 생성"""
        rows = []

        for i, change in enumerate(changes, 1):
            badge_class = change.change_type.value
            badge_text = {
                DxfChangeType.ADDED: "추가",
                DxfChangeType.DELETED: "삭제",
                DxfChangeType.MODIFIED: "수정",
            }.get(change.change_type, "?")

            location = (
                f"({change.location[0]:.1f}, {change.location[1]:.1f})" if change.location else "-"
            )

            row = f"""
                <tr>
                    <td>{i}</td>
                    <td><span class="badge {badge_class}">{badge_text}</span></td>
                    <td>{change.entity_type}</td>
                    <td>{change.layer}</td>
                    <td>{location}</td>
                </tr>"""
            rows.append(row)

        return "\n".join(rows) if rows else "<tr><td colspan='5'>변경점 없음</td></tr>"

    def _generate_image_section(self, image: np.ndarray) -> str:
        """이미지 섹션 HTML 생성 (Base64 인코딩)"""
        try:
            import cv2

            # RGB → BGR
            if len(image.shape) == 3 and image.shape[2] == 3:
                image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
            else:
                image_bgr = image

            # PNG로 인코딩
            _, buffer = cv2.imencode(".png", image_bgr)
            img_base64 = base64.b64encode(buffer).decode("utf-8")

            return f"""
                <h2>🖼️ 차이 시각화</h2>
                <div class="image-container">
                    <img src="data:image/png;base64,{img_base64}" alt="Difference Visualization">
                </div>"""

        except Exception as e:
            logger.warning(f"이미지 섹션 생성 실패: {e}")
            return ""
